#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed May 26 10:32:35 2010

import string, os, wx, wx.grid, ConfigParser
import webbrowser, tempfile
from random import choice
from xml.sax import ContentHandler
from xml.sax import make_parser
from xml.sax.handler import feature_namespaces
from iprstatsdata import IPRStatsData
from ebixml import EBIXML
from export_html import export_html
from export_xls import export_xls
from threading import Thread

# begin wxGlade: extracode
# end wxGlade

class IPRStats_Frame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MetaIPS_Frame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        self.configpath = 'iprstats.cfg'
        self.config = ConfigParser.ConfigParser()
        configfile = open(self.configpath, 'r')
        self.config.readfp(configfile)
        configfile.close()
        
        self.apps = self.config.get('general','apps').replace('\n',' ').split(', ')
        self.sessiondir = self.config.get('general','directory')
        self.chart_type = self.config.get('general','chart_type')
        if not os.path.exists(self.sessiondir):
            try:
                os.mkdir(self.sessiondir)
            except:
                self.sessiondir = tempfile.gettempdir()
        
        self.session = None
        self.dirname = ''
        self.database_results = wx.Notebook(self, -1, style=wx.NB_LEFT)

        self.tabs = {}
        self.charts = {}
        self.grids = {}

        for app in self.apps:
            self.tabs[app] = wx.Panel(self.database_results, -1, style=wx.TAB_TRAVERSAL)
            self.charts[app] = wx.StaticBitmap(self.tabs[app], -1)
            self.charts[app].Hide()
            self.grids[app] = wx.grid.Grid(self.tabs[app], -1, size=(1, 1))
        
        # Menu Bar
        self.iprstats_menu = wx.MenuBar()

        self.file_item = wx.Menu()
        self.open_item = wx.MenuItem(self.file_item, wx.ID_OPEN, "&Open...", "", wx.ITEM_NORMAL)
        self.export_html_item = wx.MenuItem(self.file_item, wx.NewId(), "Export as &HTML...", "", wx.ITEM_NORMAL)
        self.export_xls_item = wx.MenuItem(self.file_item, wx.NewId(), "Export as &XLS...", "", wx.ITEM_NORMAL)
        self.exit_item = wx.MenuItem(self.file_item, wx.ID_EXIT, "&Quit", "", wx.ITEM_NORMAL)
        self.file_item.AppendItem(self.open_item)
        self.file_item.AppendItem(self.export_html_item)
        self.file_item.AppendItem(self.export_xls_item)
        self.export_html_item.Enable(False)
        self.export_xls_item.Enable(False)
        self.file_item.AppendSeparator()
        self.file_item.AppendItem(self.exit_item)
        self.iprstats_menu.Append(self.file_item, "File")

        self.options_item = wx.Menu()
        self.use_go_lookup_item = wx.MenuItem(self.options_item, wx.NewId(), "Use &GO lookup", "", wx.ITEM_CHECK)
        self.settings_item = wx.MenuItem(self.options_item, wx.ID_PROPERTIES, "&Properties....", "", wx.ITEM_NORMAL)
        self.options_item.AppendItem(self.use_go_lookup_item)
        self.options_item.AppendItem(self.settings_item)
        self.iprstats_menu.Append(self.options_item, "Options")

        self.help_item = wx.Menu()
        self.about_item = wx.MenuItem(self.help_item, wx.ID_ABOUT, "&About", "", wx.ITEM_NORMAL)
        self.iprstats_menu.Append(self.help_item, "Help")
        self.help_item.AppendItem(self.about_item)
        self.SetMenuBar(self.iprstats_menu)
        # Menu Bar end
        
        # About information
        self.aboutinfo = wx.AboutDialogInfo()
        self.aboutinfo.SetName('IPRStats')
        self.aboutinfo.SetVersion('0.1a')
        self.aboutinfo.SetDescription('A statistical tool that eases ' +\
                'the analysis of InterProScan results by generating ' +\
                'charts and tables with links to additional information.')
        self.aboutinfo.SetWebSite('http://github.com/devrkel/IPRStats')
        self.aboutinfo.SetLicence("""Academic Free License ("AFL") v. 3.0

This Academic Free License (the "License") applies to any original work
of authorship (the "Original Work") whose owner (the "Licensor") has
placed the following licensing notice adjacent to the copyright notice
for the Original Work:

Licensed under the Academic Free License version 3.0

1) Grant of Copyright License. Licensor grants You a worldwide,
royalty-free, non-exclusive, sublicensable license, for the duration of
the copyright, to do the following:

a) to reproduce the Original Work in copies, either alone or as part of
a collective work;

b) to translate, adapt, alter, transform, modify, or arrange the
Original Work, thereby creating derivative works ("Derivative Works")
based upon the Original Work;

c) to distribute or communicate copies of the Original Work and
Derivative Works to the public, under any license of your choice that
does not contradict the terms and conditions, including Licensor's
reserved rights and remedies, in this Academic Free License;

d) to perform the Original Work publicly; and

e) to display the Original Work publicly.

2) Grant of Patent License. Licensor grants You a worldwide,
royalty-free, non-exclusive, sublicensable license, under patent claims
owned or controlled by the Licensor that are embodied in the Original
Work as furnished by the Licensor, for the duration of the patents, to
make, use, sell, offer for sale, have made, and import the Original Work
and Derivative Works.

3) Grant of Source Code License. The term "Source Code" means the
preferred form of the Original Work for making modifications to it and
all available documentation describing how to modify the Original Work.
Licensor agrees to provide a machine-readable copy of the Source Code of
the Original Work along with each copy of the Original Work that
Licensor distributes. Licensor reserves the right to satisfy this
obligation by placing a machine-readable copy of the Source Code in an
information repository reasonably calculated to permit inexpensive and
convenient access by You for as long as Licensor continues to distribute
the Original Work.

4) Exclusions From License Grant. Neither the names of Licensor, nor the
names of any contributors to the Original Work, nor any of their
trademarks or service marks, may be used to endorse or promote products
derived from this Original Work without express prior permission of the
Licensor. Except as expressly stated herein, nothing in this License
grants any license to Licensor's trademarks, copyrights, patents, trade
secrets or any other intellectual property. No patent license is granted
to make, use, sell, offer for sale, have made, or import embodiments of
any patent claims other than the licensed claims defined in Section 2.
No license is granted to the trademarks of Licensor even if such marks
are included in the Original Work. Nothing in this License shall be
interpreted to prohibit Licensor from licensing under terms different
from this License any Original Work that Licensor otherwise would have a
right to license.

5) External Deployment. The term "External Deployment" means the use,
distribution, or communication of the Original Work or Derivative Works
in any way such that the Original Work or Derivative Works may be used
by anyone other than You, whether those works are distributed or
communicated to those persons or made available as an application
intended for use over a network. As an express condition for the grants
of license hereunder, You must treat any External Deployment by You of
the Original Work or a Derivative Work as a distribution under section
1(c).

6) Attribution Rights. You must retain, in the Source Code of any
Derivative Works that You create, all copyright, patent, or trademark
notices from the Source Code of the Original Work, as well as any
notices of licensing and any descriptive text identified therein as an
"Attribution Notice." You must cause the Source Code for any Derivative
Works that You create to carry a prominent Attribution Notice reasonably
calculated to inform recipients that You have modified the Original
Work.

7) Warranty of Provenance and Disclaimer of Warranty. Licensor warrants
that the copyright in and to the Original Work and the patent rights
granted herein by Licensor are owned by the Licensor or are sublicensed
to You under the terms of this License with the permission of the
contributor(s) of those copyrights and patent rights. Except as
expressly stated in the immediately preceding sentence, the Original
Work is provided under this License on an "AS IS" BASIS and WITHOUT
WARRANTY, either express or implied, including, without limitation, the
warranties of non-infringement, merchantability or fitness for a
particular purpose. THE ENTIRE RISK AS TO THE QUALITY OF THE ORIGINAL
WORK IS WITH YOU. This DISCLAIMER OF WARRANTY constitutes an essential
part of this License. No license to the Original Work is granted by this
License except under this disclaimer.

8) Limitation of Liability. Under no circumstances and under no legal
theory, whether in tort (including negligence), contract, or otherwise,
shall the Licensor be liable to anyone for any indirect, special,
incidental, or consequential damages of any character arising as a
result of this License or the use of the Original Work including,
without limitation, damages for loss of goodwill, work stoppage,
computer failure or malfunction, or any and all other commercial damages
or losses. This limitation of liability shall not apply to the extent
applicable law prohibits such limitation.

9) Acceptance and Termination. If, at any time, You expressly assented
to this License, that assent indicates your clear and irrevocable
acceptance of this License and all of its terms and conditions. If You
distribute or communicate copies of the Original Work or a Derivative
Work, You must make a reasonable effort under the circumstances to
obtain the express assent of recipients to the terms of this License.
This License conditions your rights to undertake the activities listed
in Section 1, including your right to create Derivative Works based upon
the Original Work, and doing so without honoring these terms and
conditions is prohibited by copyright law and international treaty.
Nothing in this License is intended to affect copyright exceptions and
limitations (including "fair use" or "fair dealing"). This License shall
terminate immediately and You may no longer exercise any of the rights
granted to You by this License upon your failure to honor the conditions
in Section 1(c).

10) Termination for Patent Action. This License shall terminate
automatically and You may no longer exercise any of the rights granted
to You by this License as of the date You commence an action, including
a cross-claim or counterclaim, against Licensor or any licensee alleging
that the Original Work infringes a patent. This termination provision
shall not apply for an action alleging patent infringement by
combinations of the Original Work with other software or hardware.

11) Jurisdiction, Venue and Governing Law. Any action or suit relating
to this License may be brought only in the courts of a jurisdiction
wherein the Licensor resides or in which Licensor conducts its primary
business, and under the laws of that jurisdiction excluding its
conflict-of-law provisions. The application of the United Nations
Convention on Contracts for the International Sale of Goods is expressly
excluded. Any use of the Original Work outside the scope of this License
or after its termination shall be subject to the requirements and
penalties of copyright or patent law in the appropriate jurisdiction.
This section shall survive the termination of this License.

12) Attorneys' Fees. In any action to enforce the terms of this License
or seeking damages relating thereto, the prevailing party shall be
entitled to recover its costs and expenses, including, without
limitation, reasonable attorneys' fees and costs incurred in connection
with such action, including any appeal of such action. This section
shall survive the termination of this License.

13) Miscellaneous. If any provision of this License is held to be
unenforceable, such provision shall be reformed only to the extent
necessary to make it enforceable.

14) Definition of "You" in This License. "You" throughout this License,
whether in upper or lower case, means an individual or a legal entity
exercising rights under, and complying with all of the terms of, this
License. For legal entities, "You" includes any entity that controls, is
controlled by, or is under common control with you. For purposes of this
definition, "control" means (i) the power, direct or indirect, to cause
the direction or management of such entity, whether by contract or
otherwise, or (ii) ownership of fifty percent (50%) or more of the
outstanding shares, or (iii) beneficial ownership of such entity.

15) Right to Use. You may use the Original Work in all ways not
otherwise restricted or conditioned by this License or by law, and
Licensor promises not to interfere with or be responsible for such uses
by You.

16) Modification of This License. This License is Copyright © 2005
Lawrence Rosen. Permission is granted to copy, distribute, or
communicate this License without modification. Nothing in this License
permits You to modify this License as applied to the Original Work or to
Derivative Works. However, You may modify the text of this License and
copy, distribute or communicate your modified version (the "Modified
License") and apply it to other original works of authorship subject to
the following conditions: (i) You may not indicate in any way that your
Modified License is the "Academic Free License" or "AFL" and you may not
use those names in the name of your Modified License; (ii) You must
replace the notice specified in the first paragraph above with the
notice "Licensed under <insert your license name here>" or with a notice
of your own that is not confusingly similar to the notice in this
License; and (iii) You may not claim that your original works are open
source software unless your Modified License has been approved by Open
Source Initiative (OSI) and You comply with its license review and
certification process.
""")
        self.aboutinfo.AddDeveloper('David Vincent')
        self.aboutinfo.AddDeveloper('Ryan Kelly')
        self.aboutinfo.AddDeveloper('Iddo Friedberg')

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnOpen, self.open_item)
        self.Bind(wx.EVT_MENU, self.OnExportHTML, self.export_html_item)
        self.Bind(wx.EVT_MENU, self.OnExportXLS, self.export_xls_item)
        self.Bind(wx.EVT_MENU, self.OnExit, self.exit_item)
        self.Bind(wx.EVT_MENU, self.OnSettings, self.settings_item)
        self.Bind(wx.EVT_MENU, self.OnAbout, self.about_item)
        self.Bind(wx.grid.EVT_GRID_CELL_LEFT_CLICK, self.OnCellLeftClick)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MetaIPS_Frame.__set_properties
        self.SetTitle("IPRStats")
        self.SetSize((740, 600))

        for app in self.apps:
            self.charts[app].SetSize((1,1))
            self.grids[app].CreateGrid(0, 3)
            self.grids[app].DisableDragRowSize()
            self.grids[app].SetColLabelValue(0, "Name")
            self.grids[app].SetColLabelValue(1, "Count")
            self.grids[app].SetColLabelValue(2, "Link")
            self.grids[app].SetRowLabelSize(0)
            self.grids[app].SetColSize(0,250)
            self.grids[app].SetColSize(1,150)
            self.grids[app].SetColSize(2,280)
            self.tabs[app].SetBackgroundColour('white')
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MetaIPS_Frame.__do_layout
        main_sizer = wx.FlexGridSizer(1, 1, 0, 0)
        for app in self.apps:
            sizer = wx.FlexGridSizer(2, 1, 0, 0)
            sizer.Add(self.charts[app], 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
            sizer.Add(self.grids[app], 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
            self.tabs[app].SetSizer(sizer)
            self.database_results.AddPage(self.tabs[app], app)
            sizer.AddGrowableRow(1)
            sizer.AddGrowableCol(0)
        main_sizer.AddGrowableRow(0)
        main_sizer.AddGrowableCol(0)
        main_sizer.Add(self.database_results, 0, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        #self.main_sizer.Fit(self)
        self.Layout()
        self.SetSize((840, 600))
        # end wxGlade

    def OnOpen(self, event): # wxGlade: MetaIPS_Frame.<event_handler>
        """ Open a file"""
        dlg = wx.FileDialog(self, "Choose a file", self.dirname, "", "XML out (*.out)|*.out|XML (*.xml)|*.xml|View all files (*.*)|*.*", wx.OPEN)
        if dlg.ShowModal() == wx.ID_OK:
            self.filename = dlg.GetFilename()
            self.dirname = dlg.GetDirectory()
            
            # Create a random ID
            chars = string.letters + string.digits
            self.session = ''.join([choice(chars) for i in xrange(8)])
            
            parsethread = ParseXMLFile(os.path.join(self.dirname, self.filename),
                         self.session, self.config, self.sessiondir)
            dialog = wx.ProgressDialog( 'Progress', 'Opening ' + self.filename +'...', maximum = 3 )
            
            parsethread.start()
            while parsethread.isAlive():
                wx.Sleep(0.1)
                dialog.Update(1, "Parsing XML file...")
            parsethread.join()
                
            dialog.Update(2, "Retrieving parsed data...")
            self.PopulateGUI()
            dialog.Update(3, "Done!")
            dialog.Destroy()
            
            self.export_html_item.Enable()
            self.export_xls_item.Enable()
        dlg.Destroy()
    
    def OnExportHTML(self, event): # wxGlade: MetaIPS_Frame.<event_handler>
        """ Open a file"""
        dlg = wx.DirDialog(self, "Choose a folder", self.dirname, wx.OPEN)
        if dlg.ShowModal() == wx.ID_OK:
            self.dirname = dlg.GetPath()
            html = export_html(self.session, self.config)
            html.export(directory=self.dirname, chart=self.chart_type)
        dlg.Destroy()
    
    def OnExportXLS(self, event): # wxGlade: MetaIPS_Frame.<event_handler>
        """ Save as an .xls file"""
        dlg = wx.FileDialog(self, "Save as file", self.dirname, "", "*.xls", wx.SAVE)
        if dlg.ShowModal() == wx.ID_OK:
            self.filename = dlg.GetFilename()
            self.dirname = dlg.GetDirectory()
            if self.filename[-4:] != '.xls': self.filename += '.xls'
            xls = export_xls(self.session, self.config)
            xls.export(filename=os.path.join(self.dirname, self.filename))
        dlg.Destroy()
    
    def OnExit(self, event):
        # via wx.EVT_CLOSE event, also triggers exit dialog
        self.Close(True)
        
    def OnSettings(self, event):
        dlg = SettingsDlg(None, -1, 'Change Settings', self.config)
        if dlg.ShowModal() == wx.ID_OK:
            self.sessiondir = dlg.SessionDirTxt.GetValue()
            self.chart_type = dlg.ChartTypeCmb.GetValue().lower()
            self.config.set('general', 'directory', self.sessiondir)
            self.config.set('general', 'chart_type', self.chart_type)
            self.config.set('general', 'go_lookup', dlg.GOLookupCmb.GetValue())
            self.config.set('general', 'max_chart_results', dlg.MaxChartSpn.GetValue())
            self.config.set('general', 'max_table_results', dlg.MaxTableSpn.GetValue())
            self.config.set('local db', 'use_sqlite', str(dlg.LDBUseSqliteChk.GetValue()))
            self.config.set('local db', 'host', dlg.LDBHostTxt.GetValue())
            self.config.set('local db', 'user', dlg.LDBUserTxt.GetValue())
            self.config.set('local db', 'passwd', dlg.LDBPasswrdTxt.GetValue())
            self.config.set('local db', 'port', dlg.LDBPortSpn.GetValue())
            self.config.set('local db', 'db', str(dlg.LDBDatabaseTxt.GetValue()))
            self.config.set('go db', 'host', dlg.GDBHostTxt.GetValue())
            self.config.set('go db', 'user', dlg.GDBUserTxt.GetValue())
            self.config.set('go db', 'passwd', dlg.GDBPasswrdTxt.GetValue())
            self.config.set('go db', 'port', dlg.GDBPortSpn.GetValue())
            self.config.set('go db', 'db', str(dlg.GDBDatabaseTxt.GetValue()))
            configfile = open(self.configpath, 'w')
            self.config.write(configfile)
            configfile.close
            configfile = open(self.configpath,'r')
            self.config.readfp(configfile)
            configfile.close()
        dlg.Destroy()

    def OnAbout(self, event): # wxGlade: MetaIPS_Frame.<event_handler>
        wx.AboutBox(self.aboutinfo)
    
    def PopulateGUI(self):
        ipsstat = IPRStatsData(self.session, self.config)
        for app in self.apps:
            ipsstat.init_match_data(app)
            
            counts = ipsstat.get_counts(app)
            chart_filename = os.path.join(self.sessiondir,self.session,app.lower()+'_matches.png')

            if ipsstat.get_chart(counts, app+' Matches', chart_filename, self.chart_type):
                chart_img = wx.Bitmap(chart_filename, wx.BITMAP_TYPE_ANY)
                self.charts[app].SetBitmap(chart_img)
                self.charts[app].SetMinSize(chart_img.GetSize())
                self.charts[app].Show()
            else:
                self.charts[app].Hide()
                
                
            r = 0
            current_id = ''
            if self.grids[app].GetNumberRows() > 0:
                self.grids[app].DeleteRows(0, self.grids[app].GetNumberRows(), False)
                
            while True:
                row = ipsstat.get_link_data_row()
                if not row:
                    break

                link_font = wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, True)
                if row[0] != current_id:
                    current_id = row[0]
                    self.PopulateGridRow(app,row[1],row[3],row[2],link_font,r)
                    r += 1
                    
                self.PopulateGridRow(app,'',row[4],row[5],link_font,r)
                r += 1;
            self.grids[app].AutoSizeColumns()
            self.tabs[app].Fit()
                
    def PopulateGridRow(self, app, cell1, cell2, cell3, link_font, rownum):
        self.grids[app].AppendRows()
        self.grids[app].SetCellValue(rownum, 0, cell1)
        self.grids[app].SetCellValue(rownum, 1, str(cell2))
        self.grids[app].SetCellValue(rownum, 2, str(cell3))
        self.grids[app].SetCellFont (rownum, 2, link_font)
        self.grids[app].SetCellTextColour(rownum, 2, 'blue')
        self.grids[app].SetReadOnly(rownum, 0)
        self.grids[app].SetReadOnly(rownum, 1)
        self.grids[app].SetReadOnly(rownum, 2)
    
    def OnCellLeftClick(self, event):
        grid = event.GetEventObject()
        text = grid.GetCellValue(event.GetRow(), event.GetCol())
        if text[0:7] == 'http://':
            webbrowser.open(text)
        event.Skip()
        
class ParseXMLFile(Thread):
    def __init__(self, filename, session, config, sessiondir=tempfile.gettempdir()):
        Thread.__init__(self)
        self.filename = filename
        self.session = session
        self.config = config
        self.sessiondir=sessiondir
    
    def run(self):
        # Create a parser
        parser = make_parser()
        parser.setFeature(feature_namespaces, 0)
        
        # Create a random ID
        session_dir = os.path.join(self.sessiondir, self.session)
        os.mkdir(session_dir)

        # Create the Handler
        exh = EBIXML(self.session, config=self.config, outfile=open(os.path.join(session_dir, self.session+'.sql'),"w"))

        # Parse file into DB
        parser.setContentHandler(exh)
        parser.parse(self.filename)
        del parser
    
# end of class MetaIPS_Frame

class SettingsDlg(wx.Dialog):
    def __init__(self, parent, id, title, config):
        # begin wxGlade: SettingsDlg.__init__
        #kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        self.config = config
        self.dirname = config.get('general','directory')

        wx.Dialog.__init__(self, parent, id, title)
        self.Tabs = wx.Notebook(self, -1, style=0)
        self.DBSettingsTab = wx.Panel(self.Tabs, -1)
        self.LDBSzr_staticbox = wx.StaticBox(self.DBSettingsTab, -1, "Local database")
        self.GDBSzr_staticbox = wx.StaticBox(self.DBSettingsTab, -1, "GO database")
        self.GeneralTab = wx.Panel(self.Tabs, -1)
        self.SessionDirLbl = wx.StaticText(self.GeneralTab, -1, "Session directory:  ")
        self.SessionDirBtn = wx.Button(self.GeneralTab, -1, "...")
        self.ChartTypeLbl = wx.StaticText(self.GeneralTab, -1, "Chart type:  ")
        self.GOLookupLbl = wx.StaticText(self.GeneralTab, -1, "GO lookup:  ")
        self.MaxChartLbl = wx.StaticText(self.GeneralTab, -1, "Max chart results:  ")
        self.MaxTableLbl = wx.StaticText(self.GeneralTab, -1, "Max table results:  ")
        self.LDBUseSqliteLbl = wx.StaticText(self.DBSettingsTab, -1, "Use SQLite:  ")
        self.LDBHostLbl = wx.StaticText(self.DBSettingsTab, -1, "Host:  ")
        self.LDBUserLbl = wx.StaticText(self.DBSettingsTab, -1, "User:  ")
        self.LDBPasswrdLbl = wx.StaticText(self.DBSettingsTab, -1, "Password: ")
        self.LDBPortLbl = wx.StaticText(self.DBSettingsTab, -1, "Port:  ")
        self.LDBDatabaseLbl = wx.StaticText(self.DBSettingsTab, -1, "Database:  ")
        self.GDBHostLbl = wx.StaticText(self.DBSettingsTab, -1, "Host:  ")
        self.GDBUserLbl = wx.StaticText(self.DBSettingsTab, -1, "User:  ")
        self.GDBPasswrdLbl = wx.StaticText(self.DBSettingsTab, -1, "Password: ")
        self.GDBPortLbl = wx.StaticText(self.DBSettingsTab, -1, "Port:  ")
        self.GDBDatabaseLbl = wx.StaticText(self.DBSettingsTab, -1, "Database:  ")
        self.ApplyBtn = wx.Button(self, wx.ID_APPLY, "")
        self.CancelBtn = wx.Button(self, wx.ID_CANCEL, "")
        self.OKBtn = wx.Button(self, wx.ID_OK, "")
        self.PopulateDialog()
        
        self.Bind(wx.EVT_CHECKBOX, self.OnUseSqlite, self.LDBUseSqliteChk)
        self.Bind(wx.EVT_BUTTON, self.OnChooseSessionDir, self.SessionDirBtn)
        
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SettingsDlg.__set_properties
        self.SetTitle("Change properties...")
        
        if self.config.get('general','chart_type').lower() == 'google':
            self.ChartTypeCmb.SetSelection(0)
        else:
            self.ChartTypeCmb.SetSelection(1)
            
        if self.config.getboolean('general','go_lookup'):
            self.GOLookupCmb.SetSelection(0)
        else:
            self.GOLookupCmb.SetSelection(1)
        
        self.LDBUseSqliteChk.SetValue(self.config.getboolean('local db','use_sqlite'))
        
        if self.LDBUseSqliteChk.GetValue():
            self.LDBHostTxt.Disable()
            self.LDBUserTxt.Disable()
            self.LDBPasswrdTxt.Disable()
            self.LDBPortSpn.Disable()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SettingsDlg.__do_layout
        MainSzr = wx.FlexGridSizer(2, 1, 0, 0)
        BtnSzr = wx.FlexGridSizer(1, 3, 0, 0)
        DBSzr = wx.BoxSizer(wx.HORIZONTAL)
        GDBSzr = wx.StaticBoxSizer(self.GDBSzr_staticbox, wx.HORIZONTAL)
        GDBOptionsSzr = wx.FlexGridSizer(6, 2, 3, 0)
        LDBSzr = wx.StaticBoxSizer(self.LDBSzr_staticbox, wx.HORIZONTAL)
        LDBOptionsSzr = wx.FlexGridSizer(6, 2, 3, 0)
        
        GeneralSzr = wx.FlexGridSizer(5, 3, 3, 0)
        GeneralSzr.Add(self.SessionDirLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.SessionDirTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.SessionDirBtn, 0, wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.ChartTypeLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.ChartTypeCmb, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add((1,1), 0, wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.GOLookupLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.GOLookupCmb, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add((1,1), 0, wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.MaxChartLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.MaxChartSpn, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add((1,1), 0, wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.MaxTableLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GeneralSzr.Add(self.MaxTableSpn, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        

        self.GeneralTab.SetSizer(GeneralSzr)
        GeneralSzr.AddGrowableCol(1)
        
        LDBOptionsSzr.Add(self.LDBUseSqliteLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBUseSqliteChk, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBHostLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBHostTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBUserLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBUserTxt, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBPasswrdLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBPasswrdTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBPortLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBPortSpn, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBDatabaseLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.Add(self.LDBDatabaseTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        LDBOptionsSzr.AddGrowableCol(1)
        LDBSzr.Add(LDBOptionsSzr, 1, wx.EXPAND, 0)
        DBSzr.Add(LDBSzr, 1, wx.EXPAND, 0)
        
        DBSzr.Add((5, 20), 0, wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add((5,20), 0, wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add((5,20), 0, wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBHostLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBHostTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBUserLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBUserTxt, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBPasswrdLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBPasswrdTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBPortLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBPortSpn, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBDatabaseLbl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.Add(self.GDBDatabaseTxt, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        GDBOptionsSzr.AddGrowableCol(1)
        GDBSzr.Add(GDBOptionsSzr, 1, wx.EXPAND, 0)
        DBSzr.Add(GDBSzr, 1, wx.EXPAND, 0)
        
        self.DBSettingsTab.SetSizer(DBSzr)
        self.Tabs.AddPage(self.GeneralTab, "General")
        self.Tabs.AddPage(self.DBSettingsTab, "Database settings")
        MainSzr.Add(self.Tabs, 1, wx.EXPAND, 0)
        
        BtnSzr.Add(self.ApplyBtn, 0, wx.ADJUST_MINSIZE, 0)
        BtnSzr.Add(self.CancelBtn, 0, wx.ADJUST_MINSIZE, 0)
        BtnSzr.Add(self.OKBtn, 0, wx.ADJUST_MINSIZE, 0)
        MainSzr.Add(BtnSzr, 1, wx.ALIGN_RIGHT, 0)
        
        self.SetSizer(MainSzr)
        MainSzr.Fit(self)
        MainSzr.AddGrowableRow(0)
        MainSzr.AddGrowableCol(0)
        self.Layout()
        # end wxGlade
    
    def PopulateDialog(self):
        self.SessionDirTxt = wx.TextCtrl(self.GeneralTab,    -1, self.config.get('general','directory'))
        self.ChartTypeCmb  = wx.ComboBox(self.GeneralTab,    -1, choices=['google', 'pylab'], style=wx.CB_DROPDOWN)
        self.GOLookupCmb   = wx.ComboBox(self.GeneralTab,    -1, choices=['true','false'], style=wx.CB_DROPDOWN)
        self.MaxChartSpn   = wx.SpinCtrl(self.GeneralTab, -1, self.config.get('general','max_chart_results'), min=0, max=35)
        self.MaxTableSpn   = wx.SpinCtrl(self.GeneralTab, -1, self.config.get('general','max_table_results'), min=0, max=10000)
        self.LDBUseSqliteChk=wx.CheckBox(self.DBSettingsTab, -1, '')
        self.LDBHostTxt    = wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('local db','host'))
        self.LDBUserTxt    = wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('local db','user'))
        self.LDBPasswrdTxt = wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('local db','passwd'), style=wx.TE_PASSWORD)
        self.LDBPortSpn    = wx.SpinCtrl(self.DBSettingsTab, -1, self.config.get('local db','port'), min=0, max=10000)
        self.LDBDatabaseTxt= wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('local db','db'))
        self.GDBHostTxt    = wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('go db','host'))
        self.GDBUserTxt    = wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('go db','user'))
        self.GDBPasswrdTxt = wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('go db','passwd'), style=wx.TE_PASSWORD)
        self.GDBPortSpn    = wx.SpinCtrl(self.DBSettingsTab, -1, self.config.get('go db','port'), min=0, max=10000)
        self.GDBDatabaseTxt= wx.TextCtrl(self.DBSettingsTab, -1, self.config.get('go db','db'))

    def OnChooseSessionDir(self, event):
        if not self.dirname: self.dirname = ''
        dlg = wx.DirDialog(self, "Choose a folder", self.dirname, wx.OPEN)
        if dlg.ShowModal() == wx.ID_OK:
            self.dirname = dlg.GetPath()
            self.SessionDirTxt.SetValue(self.dirname)
        dlg.Destroy()

    def OnUseSqlite(self, event):
        if self.LDBUseSqliteChk.GetValue():
            self.LDBHostTxt.Disable()
            self.LDBUserTxt.Disable()
            self.LDBPasswrdTxt.Disable()
            self.LDBPortSpn.Disable()
        else:
            self.LDBHostTxt.Enable()
            self.LDBUserTxt.Enable()
            self.LDBPasswrdTxt.Enable()
            self.LDBPortSpn.Enable()

# end of class SettingsDlg


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    metaips_frame = IPRStats_Frame(None, -1, "")
    app.SetTopWindow(metaips_frame)
    metaips_frame.Show()
    app.MainLoop()
